---
- name: Create 3 hosts for OpenShift TestDrive@Ops{{ ':' }} Master, Infra and a Node
  hosts: localhost
  connection: connection
  gather_facts: False
  vars_files:
     - gce/authentication
     - gce/defaults
  tasks:
     - include: commons/setting_defaults.yaml

     - name: email is not defined
       fail: msg="email is not defined"
       when: email is not defined

     - name: Obtaing only the username from email
       set_fact: username={{ email | regex_replace('[@](.*)$', '') }}

     - set_fact: openshift_master="{{ username }}-master"
     - set_fact: openshift_infra="{{ username }}-infra"
     - set_fact: openshift_node="{{ username }}-node"

     - name: Check if an instance exists{{ ':' }} {{ openshift_master }}
       gce:
         instance_names: "{{ openshift_master }}"
         zone: "{{ zone }}"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       register: master_instance_status

     - debug: var=master_instance_status

#     - name: Create an instance only if it doesn't exist{{ ':' }} {{ openshift_master }}
