- hosts: localhost
  connection: local
  gather_facts: False
  vars:
     attendees: "{{ lookup('file', 'ops-attendees.txt').split('\n') }}"
  tasks:
     - set_fact: line_selected={{ item }}
       with_items: "{{ attendees }}"
       when: "{{ email in item }}"

     - debug: var=line_selected

     - set_fact: user_id={{ line_selected.split(',')[0] }}
     - set_fact: name={{ line_selected.split(',')[1] }}

     - debug: var=user_id
