apiVersion: v1
kind: BuildConfig
metadata:
  name: deploy-one
spec:
  triggers:
    - type: GitHub
      github:
        secret: githubtasks
    - type: Generic
      generic:
        secret: generictasks
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
           stage ('Build') {
             git 'https://github.com/latam-tech-office/openshift-tasks-testdrive'
             sh "mvn clean install -s configuration/cicd-settings.xml -DskipTests=true"
           }
   
           stage('Deploy') {
             sh "oc project application-canary"
             sh "oc start-build tasks-one-app --from-file target/openshift-tasks.war --follow --wait=true -n application-canary"
           }
        }
    type: JenkinsPipeline
    type: Generic
status:
  lastVersion: 0
