---
- name: "Deployment AB: Preparing environment for Application"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_file:
     - deployment-ab.definition
  tasks:
     - name: "Create Developer Tooling: {{ jenkins_namespace }}"
       command: oc new-project {{ jenkins_namespace }} --display-name="Developer Tooling"
       ignore_errors: True

     - name: "Select Project: {{ jenkins_namespace }}"
       command: oc project {{ jenkins_namespace }}"

     - name: Provisioning all Developer Tooling for AB Deployment
       command: oc new-app "{{ item }}"
       with_items: 
          - "jenkins-ephemeral"
          - "https://raw.githubusercontent.com/OpenShiftDemos/nexus-openshift-docker/master/nexus-persistent.yaml"
       ignore_errors: True

     - name: Make sure Jenkins is able to handle {{ application_namespace }}
       command: oc policy add-role-to-user edit system:serviceaccount:{{ jenkins_namespace }}:jenkins -n {{ application_namespace }}

     - name: "Creating a Project for Deployment AB"
       command: oc new-project {{ application_namespace }} --display-name="Deployment AB technique"
       ignore_errors: True

     - name: "Select Project: {{ application_namespace }}"
       command: oc project {{ application_namespace }}

     - name: Deleting any existing resources
       command: "{{ item }}"
       with_items:
          - "oc delete all -l app=wildfly-mysql"
          - "oc delete secrets -l app=wildfly-mysql"
       ignore_errors: True

     - name: Creating application {{ application_blue }}
       command: oc new-app -f https://raw.githubusercontent.com/latam-tech-office/testdrive-cicd/master/ocp/template/wildfly-mysql.yaml -p APPLICATION_NAME={{ application_blue }}

     - name: Deleting an ImageStream/wildfly-mysql to avoid collision
       command: oc delete is/wildfly-mysql

     - name: Creating application {{ application_green }}
       command: oc new-app -f https://raw.githubusercontent.com/latam-tech-office/testdrive-cicd/master/ocp/template/wildfly-mysql.yaml -p APPLICATION_NAME={{ application_green }}

     - name: Making sure DeploymentConfig is using Rolling Strategy
       command: oc patch dc/{{ item }} --patch='{"spec":{"strategy":{"type":"Rolling"}}}'
       with_items:
          - "{{ application_blue }}-app"
          - "{{ application_green }}-app"    

     - name: Making sure the Pod is ready when application is ready
       command: oc set probe dc/{{ item }} --readiness --initial-delay-seconds=20 --period-seconds=15 --get-url=http://:8080/ws/ping
       with_items:
          - "{{ application_blue }}-app"
          - "{{ application_green }}-app"   

     - name: Deleting existing routes
       command: oc delete route {{ item }}
       with_items:
          - "{{ application_blue }}-app"
          - "{{ application_green }}-app"

     - name: Creating a single route
       command: oc expose service/{{ application_blue }}-app --name=tasks --hostname={{ application_namespace }}.{{ cloudapps }}
       
     - name: Creating environment variables for each application
       command: oc env dc/{{ item.deploymentConfig }} DEPLOYMENT_NAME="{{ item.value }}"
       with_items:
          - { deploymentConfig: "{{ application_blue }}-app", value: "BLUE" }
          - { deploymentConfig: "{{ application_green }}-app", value: "GREEN" }

     - name: Creating all the necessary BuildConfig (which will be available at Jenkins)
       command: oc create -n {{ jenkins_namespace }} -f {{ item }}
       with_items: 
          - deploy-blue.yaml
          - deploy-green.yaml
          - switch-to-blue.yaml
          - switch-to-green.yaml
