apiVersion: v1
kind: BuildConfig
metadata:
  name: deploy-blue
spec:
  triggers:
    - type: GitHub
      github:
        secret: githubtasks
    - type: Generic
      generic:
        secret: generictasks
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
           stage ('Build') {
             git 'https://github.com/latam-tech-office/openshift-tasks-testdrive'
             sh "mvn clean install -s configuration/cicd-settings.xml -DskipTests=true"
           }
   
           stage('Deploy') {
             sh "oc project application-ab"
             sh "oc start-build tasks-blue-app --from-file target/openshift-tasks.war --follow --wait=true -n application-ab"
           }
        }
    type: JenkinsPipeline
    type: Generic
status:
  lastVersion: 0
